services:
  app:
    build: 
      dockerfile: dockerfile
      context: .
    ports:
      - "3030:3030"
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5462:5432"